### PR TITLE
feat(docker): Implement support for Docker

### PR DESCRIPTION
**Pull request by wlinator**
This PR proposes the following changes:

- Add `Dockerfile` and `docker-compose.yml`, which can be utilized to build and run **llmcord.py** as a container.
- Add `requirements.txt`, which is helpful for both bare-metal and Docker configurations.
- Update `README.md` to explain the available installation methods clearly.
- Update `.gitignore` to allow these new changes to be added.

**Additionally:**
By using `requirements.txt`, the user can simply run `pip install -r requirements.txt` and have all the packages installed for them with the supported versions instead of having to specify each individual package.

### CODE REVIEW

**Comment by jakobdylanc** [comment]
Thanks for this!

A recent improvement I made to llmcord.py is that config.json can be modified at any time, and the new settings are active instantly without having to restart the bot.

Your docker approach seems to break this functionality since you're copying config.json into the container. So then if the user tries to edit config.json outside of the container, nothing happens.

Can this be improved?

**Comment by wlinator** [comment]
> Can this be improved?

Certainly, the previous commit mounts `config.json` to it's respective location in the container, allowing you to edit it during runtime.

**Comment by jakobdylanc** [comment]
It seems that, in Linux, using certain text editors can break the config.json bind mount: https://github.com/moby/moby/issues/15793#issuecomment-135411504

**Comment by wlinator** [comment]
> It's not really a bug, just how linux works.

That's quite unfortunate, I added a note to README that references this issue.

**Pull request merged**
